### ISSUE TITLE
Kubernetes Manifests

### ISSUE THREAD

**Issue by MarkCupitt** [centerofci/mathesar#2707]
## Problem
We are investigating if we can convert this into a set of Kubernetes Manifests. We use `kubectl` for deployments (mostly) which supports templating (Jinja)  and sourcing jinja vars from env vars.

## Proposed solution
Has anyone else attempted this, any interest if we make it generic for use as a K8s deployment?

**Comment by rajatvijay** [comment]
@kgodey @mathemancer can you take a look?

**Comment by kgodey** [comment]
Tracked in #2509. @silentninja should work out how to integrate this into the installation improvements plan.

**Comment by silentninja** [comment]
I am removing this issue from the 0.1.3 milestone and moving it to the next release. Kubernetes manifest is quite similar to our docker-compose and there are plans to refactor our docker-compose maybe in our next release. I think it would be better to work on this when we refactor the docker-compose.

**Comment by domdomegg** [comment]
In case it's helpful for someone, this is how we've deployed mathesar on Kubernetes (assumes cert-manager and ingress-nginx for the ingress block)

<details><summary>Example Kubernetes configuration</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mathesar-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mathesar
  template:
    metadata:
      labels:
        app: mathesar
    spec:
      containers:
      - env:
        - name: SECRET_KEY
          # A unique random string used by Django for cryptographic signing
          # Generate a new key with:
          # openssl rand -base64 39 | cut -c1-50
          value: < TODO >
        - name: DJANGO_DATABASE_URL
          # A Postgres connection string of the database used for Mathesar’s internal usage.
          # Example format:
          # postgres://user:password@hostname:port/database_name
          value: < TODO >
        - name: MATHESAR_DATABASES
          # Names and connection information for databases managed by Mathesar. These databases will be accessible through the UI.
          # Format: (unique_id|connection_string),(unique_id|connection_string),...
          # e.g. (db1|postgresql://u:p@example.com:5432/db1),(db2|postgresql://u:p@example.com:5432/db2)
          value: < TODO >
        - name: ALLOWED_HOSTS
          value: '*'
        image: mathesar/mathesar-prod:latest
        name: mathesar
---
apiVersion: v1
kind: Service
metadata:
  name: mathesar-svc
  namespace: default
spec:
  ports:
  - name: default
    port: 80
    targetPort: 8000
  selector:
    app: mathesar
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-issuer
    kubernetes.io/ingress.class: nginx
  name: mathesar-ingress
  namespace: default
spec:
  rules:
  - host: mathesar.ourdomain.com
    http:
      paths:
      - backend:
          service:
            name: mathesar-svc
            port:
              name: default
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - mathesar.ourdomain.com
    secretName: mathesar-certificate
```

</details>
