### ISSUE TITLE
Error when following the documentation to disable the docker-compose default database

### ISSUE THREAD

**Issue by silentninja** [centerofci/mathesar#2885]
## Description
After following the [documentation](https://github.com/centerofci/mathesar/blob/develop/docs/docs/configuration/customize-docker-compose.md#disable-the-default-database-server--disable-db-service) to disable the database that comes by default in the docker-compose.yml file we provide, the tester ended with the following error when trying to run the mathesar service

```
$ /etc/mathesar# sudo docker compose -f docker-compose.yml up service -d
validating /etc/mathesar/docker-compose.yml: services.service.depends_on must be a list
```

The docker-compose.yml file:
```
services:
  # ...
  service:
    # ...
    volumes:
      - static:/code/static
      - media:/code/media

    depends_on:
      # Comment the below field to disable starting the database service automatically
      # db:
      #  condition: service_healthy
 ```
